typography_spectrum: 0.5821009246408386
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.9269264506732142
  lightness: 0.49345116749977563
  saturation: 0.6163242348335167
  rhythmicContrast: 0.5259029399117658
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7207273858496089
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Eric Wooley
  email: ericwooley@gmail.com
name: ericwooley
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Eric Wooley
content: []
description: I code things
purpose: []
