name: ericwooley
favicon: null
layout_spectrum: 0.2803907215129584
typography_spectrum: 0.5173813994042575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4c5051'
    - '#3c3e3d'
    - '#0d1a1b'
    - '#6c615d'
    - '#663535'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
